{{- if .CreateRbac }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .AppProxy.AppName }}-cluster-reader
  labels:
    app: {{ .AppProxy.AppName }}
    version: {{ .Version }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - coupa-application
  verbs:
  - use
{{- end }}