apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .AppProxy.AppName }}
    version: {{ .Version }} 
  name:  {{ .AppProxy.AppName }}
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .AppProxy.AppName }}
      version: {{ .Version }}
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .AppProxy.AppName }}
        version: {{ .Version }}
    spec:
      {{- if .CreateRbac }}
      serviceAccountName: {{ .AppProxy.AppName }}
      {{- end }}
      containers:
      - name: {{ .AppProxy.AppName }}
        image: {{ if ne .DockerRegistry ""}} {{- .DockerRegistry }}/{{ .AppProxy.Image.Name }}:{{ .AppProxy.Image.Tag }} {{- else }} {{- .AppProxy.Image.Name }}:{{ .AppProxy.Image.Tag }} {{- end}}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 6000Mi
          requests:
            cpu: 200m
            memory: 200Mi
        env:
          - name: PORT
            value: "3000"
          - name: CODEFRESH_HOST
            value: {{ .CodefreshHost }}
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
