{{- if .CreateRbac }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "create", "delete"]
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - coupa-application
  verbs:
  - use
{{- end }}